version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fmd-backend
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/weights
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: always

  frontend:
    build: ./frontend
    container_name: fmd-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
